const { db, admin } = require('../firestore/firebase');

// COLLECTION REFERENCE
const PACKAGES_COLLECTION = "packages";

// --- ADD PACKAGE ---
const addPackage = async (req, res) => {
  try {
    const { id, ...data } = req.body;
    
    if (!id) {
      return res.status(400).json({ error: "Package ID is required" });
    }

    // Use .set() with the custom ID generated by frontend
    await db.collection(PACKAGES_COLLECTION).doc(id).set({
      ...data,
      lastUpdated: new Date().toISOString() // Store as ISO string or serverTimestamp depending on preference
    });

    res.status(201).json({ message: "Package added successfully", id });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// --- UPDATE PACKAGE ---
const updatePackage = async (req, res) => {
  try {
    const { id } = req.params;
    const data = req.body;

    // Remove 'id' from body if it exists to prevent overwriting doc key
    delete data.id;

    await db.collection(PACKAGES_COLLECTION).doc(id).update({
      ...data,
      lastUpdated: new Date().toISOString()
    });

    res.status(200).json({ message: "Package updated successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// --- DELETE PACKAGE ---
const deletePackage = async (req, res) => {
  try {
    const { id } = req.params;

    await db.collection(PACKAGES_COLLECTION).doc(id).delete();

    res.status(200).json({ message: "Package deleted successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

module.exports = { addPackage, updatePackage, deletePackage };